const express = require('express')
const mongoose = require('mongoose')
const route = require('./route/route')
const app = express()
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use('/', route)
mongoose.connect(process.env.mongodbStr, { useNewUrlParser: true }).then(() => console.log("mongoDb connected")).catch(err => console.log(err.message))
app.listen(process.env.PORT || 3000, function () {
    console.log("server has started on the port : ", process.env.PORT || 3000)
})